// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0NUkeXLv0PUIS1DDTj3EY5blzk0oLgy8',
    appId: '1:312632358179:web:ac1c299f123d46b613c896',
    messagingSenderId: '312632358179',
    projectId: 'tanmay-weds-ankita',
    authDomain: 'tanmay-weds-ankita.firebaseapp.com',
    storageBucket: 'tanmay-weds-ankita.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlxs6AD-6d4UR3Q8kE6QciBtZ9ZmoTLw',
    appId: '1:312632358179:android:cb2c5712554f56b913c896',
    messagingSenderId: '312632358179',
    projectId: 'tanmay-weds-ankita',
    storageBucket: 'tanmay-weds-ankita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdAwqVVqxsJJPO9YUI_DAM7Uh_LY4Xyg',
    appId: '1:312632358179:ios:9ca112bffa3c29c113c896',
    messagingSenderId: '312632358179',
    projectId: 'tanmay-weds-ankita',
    storageBucket: 'tanmay-weds-ankita.appspot.com',
    iosClientId: '312632358179-isjr6nu45kcvvk80evpknf83jij3f4q3.apps.googleusercontent.com',
    iosBundleId: 'com.app.tanmaywedsankita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdAwqVVqxsJJPO9YUI_DAM7Uh_LY4Xyg',
    appId: '1:312632358179:ios:c41e4021e4c1e87513c896',
    messagingSenderId: '312632358179',
    projectId: 'tanmay-weds-ankita',
    storageBucket: 'tanmay-weds-ankita.appspot.com',
    iosClientId: '312632358179-j3noitcp7jlehsmkb09692ju8914sbrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanmayWedsAnkita.RunnerTests',
  );
}
